//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioClase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class libros
    {
        public decimal id { get; set; }
        public string autor { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string editorial { get; set; }
        public string estado { get; set; }
        public string genero { get; set; }
        public string nombre { get; set; }
        public string nomenclatura { get; set; }
        public Nullable<int> num_pag { get; set; }
        public Nullable<int> anio_publi { get; set; }
    }
}
